---
kind: pipeline
name: Build

steps:
  - name: Build image
    image: docker/compose
    commands:
      - docker-compose up
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock


volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  target:
    - production
  branch:
    - docker-compose
  event:
    - push
    - promote
