---
kind: pipeline
type: exec
name: Build

steps:
  - name: Build image
    commands:
      - cat /etc/os-release

trigger:
  target:
    - production
  branch:
    - docker-compose
  event:
    - push
    - promote
